#!/usr/bin/env python3
import os, sys, struct, math, time

EXT2_SUPER_MAGIC = 0xEF53
EXT2_GOOD_OLD_REV = 0
EXT2_DYNAMIC_REV = 1
EXT2_FEATURE_INCOMPAT_FILETYPE = 0x0002
EXT2_ROOT_INO = 2
EXT2_GOOD_OLD_FIRST_INO = 11
EXT2_N_BLOCKS = 15
EXT2_S_IFDIR = 0x4000
EXT2_S_IFREG = 0x8000
EXT2_FT_REG_FILE = 1
EXT2_FT_DIR = 2


def parse_size(s):
    s = s.strip().upper()
    mult = 1
    if s.endswith('K'):
        mult = 1024; s = s[:-1]
    elif s.endswith('M'):
        mult = 1024 * 1024; s = s[:-1]
    elif s.endswith('G'):
        mult = 1024 * 1024 * 1024; s = s[:-1]
    return int(s) * mult


def le16(v): return struct.pack('<H', v & 0xffff)
def le32(v): return struct.pack('<I', v & 0xffffffff)

def write_at(img, off, data):
    img[off:off + len(data)] = data

def set_bit(buf, idx):
    i = idx - 1
    buf[i // 8] |= 1 << (i % 8)

def rec_len(name_len):
    return (8 + name_len + 3) & ~3

def dirent(ino, name, ftype, reclen=None):
    nb = name.encode('ascii')
    if reclen is None:
        reclen = rec_len(len(nb))
    return le32(ino) + le16(reclen) + bytes([len(nb), ftype]) + nb + bytes(reclen - 8 - len(nb))

def inode(mode, size, blocks512, block_ptrs, links=1):
    now = int(time.time())
    raw = bytearray(128)
    write_at(raw, 0, le16(mode | 0o644))
    write_at(raw, 2, le16(0))
    write_at(raw, 4, le32(size))
    write_at(raw, 8, le32(now))
    write_at(raw, 12, le32(now))
    write_at(raw, 16, le32(now))
    write_at(raw, 20, le32(0))
    write_at(raw, 24, le16(0))
    write_at(raw, 26, le16(links))
    write_at(raw, 28, le32(blocks512))
    write_at(raw, 32, le32(0))
    for i, b in enumerate(block_ptrs[:EXT2_N_BLOCKS]):
        write_at(raw, 40 + i * 4, le32(b))
    return raw


def make_image(path, size_arg):
    size = parse_size(size_arg)
    if size < 8 * 1024 * 1024:
        raise SystemExit('ext2 image size must be at least 8M')

    block_size = 4096
    log_block_size = 2
    blocks_count = size // block_size
    size = blocks_count * block_size
    if blocks_count > block_size * 8:
        raise SystemExit('this simple generator supports one block group only; use <=128M with 4K blocks')

    inodes_count = 1024
    inodes_per_group = inodes_count
    blocks_per_group = min(blocks_count, block_size * 8)
    first_data_block = 0
    inode_size = 128
    inode_table_blocks = (inodes_count * inode_size + block_size - 1) // block_size

    super_block = 0
    bgdt_block = 1
    block_bitmap_block = 2
    inode_bitmap_block = 3
    inode_table_block = 4
    first_file_block = inode_table_block + inode_table_blocks
    root_dir_block = first_file_block
    readme_block = first_file_block + 1
    reserved_through = readme_block

    img = bytearray(size)

    readme_data = b'Hello from a real ext2 disk image.\nThis file was generated by tools/scripts/mk_ext2_disk.py.\n'
    test_data = b''

    readme_ino = EXT2_GOOD_OLD_FIRST_INO
    test_ino = EXT2_GOOD_OLD_FIRST_INO + 1

    # Inodes 1..10 are reserved by ext2
    used_inodes = set(range(1, EXT2_GOOD_OLD_FIRST_INO)) | {readme_ino, test_ino}
    used_inode_count = len(used_inodes)

    used_blocks = set(range(0, reserved_through + 1))
    used_block_count = len(used_blocks)

    free_blocks = blocks_count - used_block_count
    free_inodes = inodes_count - used_inode_count

    sb = bytearray(1024)
    write_at(sb, 0, le32(inodes_count))
    write_at(sb, 4, le32(blocks_count))
    write_at(sb, 8, le32(0))                    # reserved blocks
    write_at(sb, 12, le32(free_blocks))
    write_at(sb, 16, le32(free_inodes))
    write_at(sb, 20, le32(first_data_block))
    write_at(sb, 24, le32(log_block_size))
    write_at(sb, 28, le32(log_block_size))       # log frag size / cluster size compatible
    write_at(sb, 32, le32(blocks_per_group))
    write_at(sb, 36, le32(blocks_per_group))     # frags/clusters per group; must fit one bitmap block
    write_at(sb, 40, le32(inodes_per_group))
    write_at(sb, 44, le32(int(time.time())))
    write_at(sb, 48, le32(int(time.time())))
    write_at(sb, 52, le16(0))                    # mnt count
    write_at(sb, 54, le16(0xffff))               # max mnt count
    write_at(sb, 56, le16(EXT2_SUPER_MAGIC))
    write_at(sb, 58, le16(1))                    # cleanly unmounted
    write_at(sb, 60, le16(1))                    # continue on errors
    write_at(sb, 62, le16(0))                    # minor rev
    write_at(sb, 64, le32(int(time.time())))
    write_at(sb, 68, le32(0))
    write_at(sb, 72, le32(0))                    # creator OS Linux
    write_at(sb, 76, le32(EXT2_DYNAMIC_REV))
    write_at(sb, 80, le16(0))
    write_at(sb, 82, le16(0))
    write_at(sb, 84, le32(EXT2_GOOD_OLD_FIRST_INO))
    write_at(sb, 88, le16(inode_size))
    write_at(sb, 90, le16(0))
    write_at(sb, 92, le32(0))                    # compatible feature flags
    write_at(sb, 96, le32(EXT2_FEATURE_INCOMPAT_FILETYPE)) # incompatible feature flags
    write_at(sb, 100, le32(0))                   # ro-compatible feature flags
    write_at(sb, 120, b'RHKERNEL_EXT2_TEST'.ljust(16, b'\0'))
    write_at(sb, 136, b'/mnt/ext2'.ljust(64, b'\0'))
    write_at(img, 1024, sb)

    gd = bytearray(32)
    write_at(gd, 0, le32(block_bitmap_block))
    write_at(gd, 4, le32(inode_bitmap_block))
    write_at(gd, 8, le32(inode_table_block))
    write_at(gd, 12, le16(free_blocks))
    write_at(gd, 14, le16(free_inodes))
    write_at(gd, 16, le16(1))                    # used dirs
    write_at(img, bgdt_block * block_size, gd)

    bb = bytearray(block_size)
    for b in used_blocks:
        set_bit(bb, b + 1)
    for b in range(blocks_count, block_size * 8):
        set_bit(bb, b + 1)
    write_at(img, block_bitmap_block * block_size, bb)

    ib = bytearray(block_size)
    for ino in used_inodes:
        set_bit(ib, ino)
    for ino in range(inodes_count + 1, block_size * 8 + 1):
        set_bit(ib, ino)
    write_at(img, inode_bitmap_block * block_size, ib)

    root = bytearray(block_size)
    pos = 0
    d = dirent(2, '.', EXT2_FT_DIR); write_at(root, pos, d); pos += len(d)
    d = dirent(2, '..', EXT2_FT_DIR); write_at(root, pos, d); pos += len(d)
    d = dirent(readme_ino, 'README.TXT', EXT2_FT_REG_FILE); write_at(root, pos, d); pos += len(d)
    last_len = block_size - pos
    write_at(root, pos, dirent(test_ino, 'test.txt', EXT2_FT_REG_FILE, last_len))
    write_at(img, root_dir_block * block_size, root)

    write_at(img, readme_block * block_size, readme_data)

    table = bytearray(inode_table_blocks * block_size)
    def put_inode(ino, raw):
        off = (ino - 1) * inode_size
        write_at(table, off, raw)
    put_inode(2, inode(EXT2_S_IFDIR | 0o755, block_size, block_size // 512, [root_dir_block], links=2))
    put_inode(readme_ino, inode(EXT2_S_IFREG | 0o644, len(readme_data), block_size // 512, [readme_block], links=1))
    put_inode(test_ino, inode(EXT2_S_IFREG | 0o644, 0, 0, [], links=1))
    write_at(img, inode_table_block * block_size, table)

    with open(path, 'wb') as f:
        f.write(img)
    print(f'wrote {path}: ext2 {size} bytes block_size={block_size} blocks={blocks_count} inodes={inodes_count}')


if __name__ == '__main__':
    if len(sys.argv) != 3:
        raise SystemExit('usage: mk_ext2_disk.py OUT.img SIZE')
    os.makedirs(os.path.dirname(sys.argv[1]) or '.', exist_ok=True)
    make_image(sys.argv[1], sys.argv[2])
