name: Build Kernel

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip curl build-essential nasm qemu-system grub-pc-bin xorriso mtools python3-venv cpio clang-format

    - name: Build kernel
      run: make build-x86_64
    - name: Upload ISO
      uses: actions/upload-artifact@v4
      with:
        name: kernel.iso
        path: dist/x86_64/kernel.iso
